---
- name: Laraval App 
  hosts: all
  remote_user: root
  become: yes

  vars_files:
    - vars/config

  tasks:
    - name: Upgrade System
      apt: upgrade=dist update_cache=yes
      become: yes

    - name: Install Apache2, PHP and dependencies
      ansible.builtin.package:
        name:
          - apache2
          - php{{ php_version }}
          - php{{ php_version }}-mbstring
          - php{{ php_version }}-xml
          - libapache2-mod-php
          - php{{ php_version }}-zip
          - php{{ php_version }}-mysql
          - php{{ php_version }}-pgsql
          - php{{ php_version }}-xml
          - php{{ php_version }}-dev
          - php{{ php_version }}-gd
          - php{{ php_version }}-curl
        state: present
        update_cache: yes

    - name: download composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer

    - name: install composer
      shell: php /tmp/composer --install-dir=/usr/local/bin
      become: yes

    - name: rename composer executable
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      become: yes

    - name: set permissions for composer file
      ansible.builtin.file:
        path: /usr/local/bin/composer
        mode: a+x
        state: file
      become: yes

    - name: Clone the laravel repo for github
      git:
        repo: "{{ repos }}"
        dest: /var/www/html/myapp
      become: yes

    - name: Take ownership of the application folder
      ansible.builtin.file:
        path: /var/www/html/myapp
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
      become: yes

    - name: Set permission for the storage folder
      ansible.builtin.file:
        path: /var/www/html/myapp/storage
        state: directory
        recurse: yes
        mode: "0777"
      become: yes

    - name: Rename and .env file
      copy:
        src: /var/www/html/myapp/.env.example
        remote_src: yes
        dest: /var/www/html/myapp/.env
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_user_id }}"
        mode: '0666'
      become: yes


    - name: edit .env to insert ip-add into server ip
      ansible.builtin.replace:
        path: /var/www/html/myapp/.env
        regexp: 'SERVER_IP'
        replace: "{{ ip_address }}"
      become: yes

    - name: input database user in .env
      ansible.builtin.replace:
        path: /var/www/html/myapp/.env
        regexp: 'DB_USR'
        replace: "{{ db_username }}"
      become: yes

    - name: input password in .env
      ansible.builtin.replace:
        path: /var/www/html/myapp/.env
        regexp: 'DB_PASSWRD'
        replace: "{{ db_password }}"
      become: yes

    - name: input dbname in .env
      ansible.builtin.replace:
        path: /var/www/html/myapp/.env
        regexp: 'database_db'
        replace: "{{ db_database }}"
      become: yes

    - name: input port in .env
      ansible.builtin.replace:
        path: /var/www/html/myapp/.env
        regexp: 'port_db'
        replace: "{{ db_port }}"
      become: yes

    - name: input connection in .env
      ansible.builtin.replace:
        path: /var/www/html/myapp/.env
        regexp: 'conn_db'
        replace: "{{ db_connection }}"
      become: yes

    - name: Install Laravel dependencies
      composer:
      # command: install
        command: update
        working_dir: /var/www/html/myapp
      environment:
        COMPOSER_ALLOW_SUPERUSER: "1"
        COMPOSER_NO_INTERACTION: "1"

    - name: copy apache config
      copy:
        src: laravel.conf
        dest: /etc/apache2/sites-available/laravel.conf
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: '0644'
      become: yes

    - name: copy laravel ssl config
      copy:
        src: laravel-le-ssl.conf
        dest: /etc/apache2/sites-available/laravel-le-ssl.conf
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
        mode: '0644'
      become: yes

    - name: enable the new config
      shell: |
        a2ensite laravel.conf
        a2dissite 000-default.conf
        a2enmod rewrite
        service apache2 restart
      become: yes

    - name: setup laravel
      shell: |
        cd /var/www/html/myapp
        php artisan key:generate
      become: yes

    - name: setup laravel
      shell: |
        cd /var/www/html/myapp
        php artisan migrate
      become: yes
